# ===========================================================================
# Plex Bot Configuration
# If you find any issues, need support, or have a suggestion for the bot, please join our support server and create a ticket, 
# https://discord.gg/eRaeJdTsPY
# Language can be changed in lang.yml
# ===========================================================================

# ===========================================================================
# BOT INFORMATION
# You must not leave them as blank!
# ===========================================================================
Version: "1.4.0" # Don't change this!
BotToken: "OTE1OTIyMzY4MDcxODgwNzI0.Gvaegg.3sDqY0kjmBGARJnB9280-pIgQ-7CmrBzsiaDeI" # If you don't know how to get it, Look at our docs: https://docs.plexdevelopment.net
LicenseKey: "LICENSE_KEY" # Copy and paste Directleaks
GuildID: "811840906037559296" # This is your server's ID, Right click on your server icon and copy ID
BotName: "Plex Bot"
EmbedColors: "#3489a8" # Hex color
LogCommands: false # If this is enabled it will log all the commands executed to the terminal
Statistics: true # Show statistics in terminal when the bot starts? (This does not affect the stats command or anything else)

SuccessEmbedColor: "#2ecc71" # Hex color
ErrorEmbedColor: "#E74C3C" # Hex color

# ===========================================================================
# BOT ACTIVITY
# ===========================================================================
BotActivitySettings:
  Enabled: true
  Type: "WATCHING" # WATCHING, PLAYING, COMPETING
  Interval: 30 # Time in seconds between status changes, It's recommended to keep it above 20-30 seconds to avoid getting ratelimited
  Statuses: # Valid Variables: {total-users}, {total-channels}, {total-messages}
    - "{total-users} users"
    - "{total-messages} messages"

# ===========================================================================
# EVENT LOGS
# ===========================================================================
# Channel create/delete logs
ChannelCreateDeleteLogs:
  Enabled: true
  ChannelID: ""

# User nickname change logs, etc..
UserUpdateLogs:
  Enabled: true
  ChannelID: ""

# Server name/icon change logs, etc..
GuildUpdateLogs:
  Enabled: true
  ChannelID: ""

# Message delete logs
MessageDeleteLogs: 
  Enabled: true
  ChannelID: ""

# Message edit logs
MessageUpdateLogs:
  Enabled: true
  ChannelID: ""

# Voice channel logs, joins, leaves, lives, server mute/unmute logs, etc..
VoiceChannelLogs: 
  Enabled: true
  ChannelID: ""

# ===========================================================================
# CHANNEL SETUP
# ===========================================================================
StaffLogsChannel: "CHANNEL_ID"

AppealLink: "" # The link users get in DMS when they get banned/timed out to appeal, for example a google forms link, leave blank to disable

# ===========================================================================
# TICKET SYSTEM
# ===========================================================================
TicketSettings:
  Enabled: false
  CategoryID: "CATEGORY_ID" # The category all tickets will be moved to when created  
  LogsChannelID: "CHANNEL_ID" # Ticket close logs/transcripts channel
  NewTicketTitle: "Support Ticket"
  NewTicketMessage: "> Thank you for contacting support.\n> Please describe your issue and await a response."
  SupportRoles: ["ROLE_ID"] # Users with these roles can view tickets, You can add multiple

TicketPanelSettings:
  PanelTitle: "Support Tickets"
  PanelMessage: "> If you need any assistance click the button below!\n> Our staff team will be shortly with you!"
  ButtonName: "Create a Ticket"
  ButtonEmoji: "üì©"
  ButtonColor: "Secondary" # Primary = blurple, Secondary = gray, Success = green, Danger = red

# If you need a better and more advanced ticket system with multiple buttons, categories, HTML transcripts, paypal invoices, ticket claiming, ticket reviews, crypto payments, and much more, You can try Plex Tickets!
# https://www.mc-market.org/resources/22209/

# ===========================================================================
# LEVELING SYSTEM
# ===========================================================================
LevelingSystem:
  Enabled: false
  ResetDataOnLeave: false # Reset user level and xp if they leave the server?
  MinXP: 10 # Minimum XP a user can get from one message
  MaxXP: 20 # Maximum XP a user can get from one message
  XPNeeded: 150 # XP multiplier each level

  LevelUpChannelID: "" # The channel where level up messages will be sent to, leave empty for the channel the user is currently in
  EnableXPCooldown: false # Enable cooldown for gaining XP to prevent spam
  XPCooldown: "20s" # XP Cooldown, 1s/1m/1h
  DisabledChannels: ["CHANNEL_ID"] # Users won't gain XP in these channels, you can add multiple, (Channel IDS), leave blank for no channels

  LevelUpMessage: "{user}, you are now level {level}" # Use {user} for the user and {level} for the new level
  StackRoles: false # Should level up roles stack? (For example, if user has level 5 role, and they level up to level 10, The bot will remove their level 5 role)
  LevelUpRoles: # Roles users get when they reach a certain level, you can add unlimited
    - level: 1
      roleID: ""

    - level: 5
      roleID: ""

    - level: 10
      roleID: ""

    - level: 20
      roleID: ""

# Rank Card Customization:
# You can find the rank card background in the commands/Leveling folder
# Replace that file to change the background, but make sure it's a png file or it won't work!
RankCard:
  ProgressBarColor: "#FFFFFF" # Hex Color
  StatusColor: "#FFFFFF" # Hex Color
  LevelColor: "#FFFFFF" # Hex Color

# ===========================================================================
# AUTO MODERATION
# ===========================================================================

# Alt Prevention System
AltPrevention:
  Enabled: true
  KickAlts: true # Kick alt accounts from the server?
  dmUser: true
  dmMessage: "We detected your account as an alt!"
  TimeLimit: "10d" # The account age limit before an account is considered an alt
  LogsChannelID: "" # Leave blank for no logs

# Blacklist Words System
BlacklistWords:
  Enabled: true
  Words: ["example1", "example2", "example3"] # Words to blacklist
  BypassPerms: ["ManageMessages"] # Users with these permissions bypass word blacklist, you can add multiple
  BypassRoles: [""] # Users with these roles bypass word blacklist, You can add multiple
  Message: "{user}, you used a blacklisted word!"

# Anti Discord Invite System
AntiInviteLinks:
  Enabled: true
  BypassPerms: ["ManageMessages"] # Users with these permissions bypass word blacklist, you can add multiple
  BypassRoles: [""] # Users with these roles bypass anti discord invites, You can add multiple
  Message: "{user}, invite links are not permitted here!"
  TimeoutUser: true # Timeout user if they send an invite link?
  TimeoutTime: "5m" # Timeout time if TimeoutUser is set to true

# Anti User Mass Mention
AntiMassMention:
  Enabled: true
  Amount: 10 # Amount of user mentions in one message before it's considered mass mention
  BypassPerms: ["ManageMessages"] # Users with these permissions bypass word blacklist, you can add multiple
  BypassRoles: [""] # Users with these roles bypass anti discord invites, You can add multiple
  Message: "{user}, mass mentions are not permitted here!"
  TimeoutUser: true # Timeout user if they mass mention?
  TimeoutTime: "5m" # Timeout time if TimeoutUser is set to true

# Anti Spam
AntiSpam:
  Enabled: true
  MsgLimit: 7 # The amount of messages that have be sent in the time specified below for it to be considered spam
  TimeLimit: "5s"
  BypassPerms: ["ManageMessages"] # Users with these permissions bypass word blacklist, you can add multiple
  BypassRoles: [""] # Users with these roles bypass anti spam, You can add multiple
  Message: "{user}, spamming is not permitted here!"
  TimeoutUser: true # Timeout user if they spam?
  TimeoutTime: "3m" # Timeout time if TimeoutUser is set to true

# ===========================================================================
# USER JOIN/LEAVE MESSAGE CONFIGURATION
# ===========================================================================
EnableWelcomeMessages: true
EnableLeaveMessages: true

WelcomeChannel: "CHANNEL_ID"
LeaveChannel: "CHANNEL_ID"

MessageType: 1 # 1 = Embed Message, 2 = Normal Message

# Variables
# {user-name} - Username without # and ping, Example
# {user} - User ping, @Example
# {user-tag} - User tag, Example#0000
# {user-createdAt} - User account creation date, for example: 06/29/2021
# {user-joinedAt} - User server join date, (ONLY WORKS IN LEAVE EMBED)
# {memberCount} - Server member count
# {guildName} - Server name

WelcomeNormalMessage: "{user} has joined the server!" # Only change this if MessageType is 2
LeaveNormalMessage: "{user} has left the server!" # Only change this if MessageType is 2

# Only change this if MessageType is 1
WelcomeEmbed: # If a string is empty it won't be added to the embed!
  EmbedColor: "Green" # Hex color
  AuthorTitle: ""
  Title: "{user-tag} has joined!"
  Description: "Created on: {user-createdAt}" # You can use \n for new lines
  Footer: "{user-tag}"
  Timestamp: true # Enable footer timestamp?
  UserIconThumbnail: true # Enable user avatar in the thumbnail?
  UserIconFooter: true # Enable user avatar in the footer?
  UserIconAuthor: false # Enable user avatar in Author section? (Only works if AuthorTitle is not blank)

# Only change this if MessageType is 1
LeaveEmbed: # If a string is empty it won't be added to the embed!
  EmbedColor: "Red" # Hex color
  AuthorTitle: ""
  Title: "{user-tag} has left!"
  Description: "Joined on: {user-joinedAt}" # You can use \n for new lines
  Footer: "{user-tag}"
  Timestamp: true # Enable footer timestamp?
  UserIconThumbnail: true # Enable user avatar in the thumbnail?
  UserIconFooter: true # Enable user avatar in the footer?
  UserIconAuthor: false # Enable user avatar in Author section? (Only works if AuthorTitle is not blank)
  UserRoles: true # Display all the roles the user had?

# ===========================================================================
# CHANNEL STATS CONFIGURATION 
# ===========================================================================
# All of these channels will automatically update every 5 minutes
MemberCount:
  Enabled: true
  ChannelID: "CHANNEL_ID" # Voice channel ID
  ChannelName: "Member Count: {total-members}" # Use {total-members} for the total amount of server members

NitroBoosterCount:
  Enabled: true
  ChannelID: "CHANNEL_ID" # Voice channel ID
  ChannelName: "Nitro Boosters: {total-boosters}" # Use {total-boosters} for the total amount of nitro boosters

# ===========================================================================
# JOIN ROLE/VERIFICATION CONFIGURATION
# ===========================================================================
JoinRoleSettings:
  Enabled: true
  JoinRoles: ["ROLE_ID"] # This is the roles users get when they join your discord server, You can add multiple
  # [!] Don't enable JoinRoles if you have the verification unverified role enabled!, Instead, add the roles you want users to get to "VerifiedRoleID"
  # [!] Don't enable JoinRoles if you have the verification unverified role enabled!, Instead, add the roles you want users to get to "VerifiedRoleID"


# Verification Types:
# BUTTON - When a user clicks the button, they get the specified role
# CAPTCHA - When a user clicks the button, the bot will reply with a captcha for the user to complete in order to get the specified role
VerificationSettings:
  Enabled: false # Enable users to verify when they join your discord server?
  DeleteAllMessages: true # Delete all user messages in the verification channel?
  ChannelID: "CHANNEL_ID" # The channel users should verify in (Button will be automatically sent)
  VerificationType: "CAPTCHA" # You can choose between "CAPTCHA" and "BUTTON"
  VerifiedRoleID: ["ROLE_ID"] # The roles users get when they successfully verify, You can add multiple
  RoleToRemove: "ROLE_ID" # The role to remove when they successfully verify, Leave blank for none
  EnableUnverifiedRole: false # Enable the Unverified role? (Automatically created and denied access to all channels other than verify channel)

VerificationEmbed:
  Title: "Verification System"
  Description: "Please verify to get full access to the server.\nClick the **button** below to get verified!"
  Image: "https://i.imgur.com/DKezUsj.png"

# Valid colors:
# Primary = blurple
# Secondary = gray
# Success = green
# Danger = red
VerificationButton:
  Name: "Verify"
  Emoji: "‚úÖ"
  Color: "Secondary"

# ===========================================================================
# GIVEAWAYS CONFIGURATION 
# ===========================================================================
EnableGiveaways: true

Giveaways:
  CanBotsWin: true # Should bots be able to win giveaways?
  EmbedColor: "#d47dad"
  EmbedColorEnd: "#000000" # Embed color when the giveaway has ended
  Reaction: "üéâ"

# ===========================================================================
# REACTION ROLES CONFIGURATION 
# ===========================================================================
EnableReactionRoles: false

ReactionRoles: # You can add unlimited reaction roles!
  - messageID: "973002160780505108" # The message reactions should be added to
    emojiName: "üõ†Ô∏è" # The emoji users have to react to get the role
    roleID: "731044654174437497" # The role users should get when they react
    channelID: "948278061542047754" # The channel the message is in

  - messageID: "973002160780505108" # The message reactions should be added to
    emojiName: "‚úÖ" # The emoji users have to react to get the role
    roleID: "731044654174437497" # The role users should get when they react
    channelID: "948278061542047754" # The channel the message is in

  - messageID: "973002160780505108" # The message reactions should be added to
    emojiName: "‚ùå" # The emoji users have to react to get the role
    roleID: "731044654174437497" # The role users should get when they react
    channelID: "948278061542047754" # The channel the message is in

# ===========================================================================
# CUSTOM COMMANDS
# ===========================================================================
CommandsEnabled: false
CommandsPrefix: "!" # The prefix for custom commands

CustomCommands: # You can add unlimited commands!
  - command: "test1"
    response: "This is a test!"
    Embed: false # Use an embed instead of a normal message?
    deleteMsg: true # Delete the message author's message when using this command? (It's recommended to leave this false if replyToUser is set to true)
    replyToUser: false # Reply to the user with the response that sent the command?

  - command: "test2"
    response: "This is a test!"
    Embed: false # Use an embed instead of a normal message?
    deleteMsg: true # Delete the message author's message when using this command? (It's recommended to leave this false if replyToUser is set to true)
    replyToUser: false # Reply to the user with the response that sent the command?

  - command: "test3"
    response: "This is a test!"
    Embed: false # Use an embed instead of a normal message?
    deleteMsg: true # Delete the message author's message when using this command? (It's recommended to leave this false if replyToUser is set to true)
    replyToUser: false # Reply to the user with the response that sent the command?

# ===========================================================================
# AUTO RESPONSES
# ===========================================================================
AutoResponse:
  Enabled: false
  MessageType: "EMBED" # You can choose between "EMBED" and "TEXT"
  Responses: # Initiator Message - Response Message, (You can add unlimited responses)
    "Server IP": "The server IP is 123.123.123.123"
    "Test": "This is a test!"

# ===========================================================================
# STAR BOARD CONFIGURATION 
# ===========================================================================
# If this is enabled, messages that get a configured amount of reactions get sent to a configured channel
StarBoard:
  Enabled: false
  ChannelID: "CHANNEL_ID" # The channel messages will be sent to
  Reactions: 5 # How many reactions required to send it to the channel?
  Emoji: "‚≠ê" # The reaction to count

# ===========================================================================
# BIRTHDAY SYSTEM CONFIGURATION 
# ===========================================================================
# Users have to set their birthday with the /setbirthday command!
BirthdaySystem:
  Enabled: false
  ChannelID: "CHANNEL_ID" # The channel to send birthday messages to
  MessageTitle: ":partying_face: Today's Birthdays!"
  Message: "Happy birthday to the following member(s)! Make sure to wish them a happy birthday!"

# ===========================================================================
# SUGGESTION SYSTEM
# ===========================================================================
SuggestionSettings:
  Enabled: false # Enable suggestion system?
  ChannelID: "CHANNEL_ID" # The channel where all the suggestions will be posted
  EnableAcceptDenySystem: true # Enable the accept and deny system for suggestions? (if this is disabled, the accept, deny buttons and status will automatically be removed)
  RemoveAllButtonsIfAcceptedOrDenied: true # Remove all buttons from a suggestion if it was accepted or denied?
  AllowedRoles: ["ROLE_ID"] # Users with these roles can accept and deny suggestions, You can add multiple roles
  LogsChannel: "CHANNEL_ID" # The channel where all upvote/downvote/accept/deny user logs will be sent to, Leave blank to disable

SuggestionStatuses:
  Pending: "üü† Pending"
  Accepted: "üü¢ Accepted"
  Denied: "üî¥ Denied"

SuggestionStatusesEmbedColors:
  Pending: "#E67E22" # The color to set the embed color to when the suggestion is pending (hex color)
  Accepted: "#2ECC71" # The color to set the embed color to when the suggestion is accepted (hex color)
  Denied: "#E74C3C" # The color to set the embed color to when the suggestion is denied (hex color)

SuggestionUpvote:
  ButtonName: "Upvote"
  ButtonEmoji: "‚¨ÜÔ∏è"
  ButtonColor: "GRAY" # BLURPLE, GRAY, GREEN, RED

SuggestionDownvote:
  ButtonName: "Downvote"
  ButtonEmoji: "‚¨áÔ∏è"
  ButtonColor: "GRAY" # BLURPLE, GRAY, GREEN, RED

SuggestionResetvote:
  ButtonName: "Reset Vote"
  ButtonEmoji: "üóëÔ∏è"
  ButtonColor: "GRAY" # BLURPLE, GRAY, GREEN, RED

SuggestionAccept:
  ButtonName: "Accept"
  ButtonEmoji: "üü¢"
  ButtonColor: "BLURPLE" # BLURPLE, GRAY, GREEN, RED

SuggestionDeny:
  ButtonName: "Deny"
  ButtonEmoji: "üî¥"
  ButtonColor: "BLURPLE" # BLURPLE, GRAY, GREEN, RED

# ===========================================================================
# MUSIC CONFIGURATION
# ===========================================================================
MusicSettings:
  Enabled: true # Enable the music system?

  # Music DJ
  EnableDJ: false # Set to false to allow everyone to use all music commands
  DJRole: "ROLE_ID"
  DisabledCommands: ['volume'] # Music commands no one can use
  AllowedUserCommands: ['play', 'queue'] # Commands anyone is allowed use, if a command isn't listed here, only DJS will be able to use it

Emojis:
  play: "‚ñ∂Ô∏è"
  stop: "‚èπÔ∏è"
  queue: "üìÑ"
  success: "‚òëÔ∏è"
  repeat: "üîÅ"
  error: "‚ùå"


# ===========================================================================
# OTHER
# ===========================================================================
EnableBackups: true